module.exports = {
    //texts
    gameSetting: 'Game Setting',
    userRank: 'User Rank',
    mg: 'mg',
    save: 'Save',
    close: 'Close',
    exitGame: 'Exit Game',
    ok: 'OK',
    cancel: 'Cancel',
    confirm: 'Confirm',
    notice: 'Notice',
    exitConfirm: 'Are you sure to exit?',
    gameSettlement: 'Game Settlement',
    eatenBy: 'You have been eaten by %s.',
    continue: 'Continue',
    finalWeight: 'Final Weight',
    eatenCount: 'Eaten Count',
    liveTime: 'Live Time',
    leftTime: 'Left Time',
    enterName: 'Enter You Name:',
    enterGame: 'Enter Game',
    nameInputHint: 'less than 8 letters',
    serverList: 'Server List:',
    noServer: 'No valid servers',
    enter: 'Enter',
    backToHall: 'Back To Hall',
    startGame: 'Start Game',
    gameEnd: 'Game End',
    eatenRank: 'Eaten Rank',
    weightRank: 'Weight Rank',
    playerName: 'Player Name',
    rank: 'Rank',
    serverDisconnect: '%s Server Disconnected',
    game: 'Game',
    world: 'World',
    backToLogin: 'Back To Login',
    gameAbnormal: 'Unknown Exception,Game Will Exit',
    enterChat: 'Enter Chat',
    send: 'Send',
    chat: 'Chat',

    //error
    unknownError: 'Unknown Error',
    timeout: 'Timeout',
    connectError: 'Connect Error',
    invalidData: 'Invalid Data',
    uselessData: 'Useless Data',
    uselessRequest: 'Useless Request',
    invalidPlayer: 'Invalid Player',
    invalidState: 'Invalid State',
    agentError: 'Agent Error',
    invaidGameToken: 'Invalid Game Token',
    expiredGameToken: 'Expired Game Token',
    invalidPlayerName: ' Player Name Cannot Inlude Any Special Characters',
    emptyPlayerName: 'Player Name Cannot Be Empty'
}