module.exports = {
    //texts
    gameSetting: 'Setting',
    userRank: 'Rank',
    mg: 'mg',
    save: 'Save',
    close: 'Close',
    exitGame: 'Exit',
    ok: 'OK',
    cancel: 'Cancel',
    confirm: 'Confirm',
    notice: 'Notice',
    exitConfirm: 'Are you sure to exit?',
    gameSettlement: 'Game Settlement',
    eatenBy: 'You have been eaten by %s.',
    continue: 'Continue',
    finalWeight: 'Weight',
    eatenCount: 'Eaten',
    liveTime: 'Live',
    leftTime: 'Left Time',
    enterName: 'Your Name:',
    enterGame: 'Enter',
    nameInputHint: 'Less than 8 letters',
    serverList: 'Server List:',
    noServer: 'No valid servers',
    enter: 'Enter',
    backToHall: 'Back',
    startGame: 'Start',
    gameEnd: 'Game End',
    eatenRank: 'Eaten',
    weightRank: 'Weight',
    playerName: 'Name',
    rank: 'Rank',
    serverDisconnect: '%s Server Disconnected',
    game: 'Game',
    world: 'World',
    backToLogin: 'Back',
    gameAbnormal: 'Unknown exception,game will exit.',
    enterChat: 'Chat',
    send: 'Send',
    chat: 'Chat',
    clearMessages: 'Clear',
    guideContent: 'Using %s to controll your entity.',

    //error
    unknownError: 'Unknown Error',
    timeout: 'Timeout',
    connectError: 'Connect Error',
    invalidData: 'Invalid Data',
    uselessData: 'Useless Data',
    uselessRequest: 'Useless Request',
    invalidPlayer: 'Invalid Player',
    invalidState: 'Invalid State',
    agentError: 'Agent Error',
    invaidGameToken: 'Invalid Game Token',
    expiredGameToken: 'Expired Game Token',
    invalidPlayerName: ' Player Name Cannot Inlude Any Special Characters',
    emptyPlayerName: 'Player Name Cannot Be Empty'
}