module.exports = {
    gameSetting: 'Game Setting',
    userRank: 'User Rank',
    mg: 'mg',
    save: 'Save',
    close: 'Close',
    exitGame: 'Exit Game',
    ok: 'OK',
    cancel: 'Cancel',
    confirm: 'Confirm',
    notice: 'Notice',
    exitConfirm: 'Are you sure to exit?',
    gameSettlement: 'Game Settlement',
    eatenBy: 'You have been eaten by %s.',
    continue: 'Continue',
    finalWeight: 'Final Weight',
    eatenCount: 'Eaten Count',
    liveTime: 'Live Time',
    leftTime: 'Left Time',
    enterName: 'Enter You Name:',
    enterGame: 'Enter Game',
    nameInputHint: 'less than 8 characters',
    serverList: 'Server List:',
    noServer: 'No valid servers',
    enter: 'Enter',
    backToHall: 'Back To Hall',
    startGame: 'Start Game',
    gameEnd: 'Game End',
    eatenRank: 'Eaten Rank',
    weightRank: 'Weight Rank',
    playerName: 'Player Name',
    rank: 'Rank'
}